package com.kiseok.pingmall.common.errors;

import lombok.AllArgsConstructor;
import lombok.Getter;
import static com.kiseok.pingmall.common.errors.ErrorConstants.*;

@Getter @AllArgsConstructor
public enum ErrorCode {

    // Account
    INVALID_INPUT_ERROR("a001", BAD_REQUEST_400, INVALID_INPUT),
    DUPLICATED_ACCOUNT_ERROR("a002", BAD_REQUEST_400, DUPLICATED_ACCOUNT),
    NOT_FOUND_ACCOUNT_ERROR("a003", NOT_FOUND_404, NOT_FOUND_ACCOUNT),
    NOT_MATCH_ACCOUNT_ID_ERROR("a004", BAD_REQUEST_400, NOT_MATCH_ACCOUNT_ID),
    EQUAL_ACCOUNT_ID_ERROR("a005", BAD_REQUEST_400, EQUAL_ACCOUNT_ID),
    UNAUTHORIZED_ACCOUNT_ERROR("a006", UNAUTHORIZED_401, UNAUTHORIZED_ACCOUNT),
    INVALID_VERIFICATION_CODE_ERROR("a007", BAD_REQUEST_400, INVALID_VERIFICATION_CODE),
    USER_NOT_VERIFIED_ERROR("a008", BAD_REQUEST_400, USER_NOT_VERIFIED),

    // Product
    NOT_FOUND_PRODUCT_ERROR("p001", NOT_FOUND_404, NOT_FOUND_PRODUCT),

    // Image
    INVALID_FILE_NAME_ERROR("i001", BAD_REQUEST_400, INVALID_FILE_NAME),
    INVALID_FILE_EXTENSION_ERROR("i002", BAD_REQUEST_400, INVALID_FILE_EXTENSION),
    NOT_FOUND_FILE_ERROR("i003", NOT_FOUND_404, NOT_FOUND_FILE),
    INVALID_FILE_ERROR("i004", BAD_REQUEST_400, INVALID_FILE),
    INVALID_FILE_PATH_ERROR("i005", BAD_REQUEST_400, INVALID_FILE_PATH),

    // Orders
    SHORTAGE_BALANCE_ERROR("o001", BAD_REQUEST_400, SHORTAGE_BALANCE),
    SHORTAGE_STOCK_ERROR("o002", BAD_REQUEST_400, SHORTAGE_STOCK),

    // Comment
    NOT_FOUND_COMMENT_ERROR("c001", NOT_FOUND_404, NOT_FOUND_COMMENT);

    private final String code;
    private final String status;
    private final String message;
}
