spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pingmall?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: didrltjr3!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

app-property:
  test-email: test@email.com
  test-password: testPW123!
  test-modified-password: modifiedPW123!
  test-name: testName
  test-balance: 200
  test-modified-name: modifiedName
  test-address: testAddress
  test-modified-address: modifiedAddress
  test-product-name: testProductName
  test-modified-product-name: modifiedProductName
  test-size: 265
  test-modified-size: 270
  test-image: testImage
  test-modified-image: modifiedImage
  test-price: 10000
  test-modified-price: 20000
  test-stock: 10
  test-modified-stock: 5

