spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pingmall?characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: didrltjr3!
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: create
  h2:
    console:
      enabled: true